controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


# index:
#     path: /hello/{name}
#     controller: 'App\Controller\DefaultController::index'
# simple:
#   path: /simplicity
#   controller: App\Controller\DefaultController::simple

